version: '3.8'

networks:
  common.network:
    driver: bridge

volumes:
  mongo.one.vol:
    name: "mongo.one.vol"

  mongo.two.vol:
    name: "mongo.two.vol"

services: 
  mongo.one.db:
    container_name: mongo.one.db
    image: mongo:latest
    networks:
      common.network:
    ports:
      - 20000:27017
    environment:
        MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo.one.vol:/data/db
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./rs-init.sh:/scripts/rs-init.sh
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo.two.db:
    container_name: mongo.two.db
    image: mongo:latest
    networks:
      common.network:
    ports:
      - 20001:27017
    depends_on:
      - mongo.one.db
    volumes:
      - mongo.two.vol:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  